### PR TITLE
Trigger click on play after skip

### LINKED ISSUE #12: Skipflix skips intro but pauses
I'm not sure when this started, but within the past week, Skipflix appears to skip the intro properly, but it pauses the video after skipping.  Is there a way to change this so that it does not automatically pause?

### PR DESCRIPTION
**Pull request by joacimastrom**
Quickfix which resolves #12. 

Not optimal or very stable, just something I cooked up quickly that works. Never used MutationObserver before, feedback is appreciated.

### CODE REVIEW

**Comment by joacimastrom** [comment]
@joaomarceloods @vitormalencar 
Are you still maintaining this?

**Comment by joaomarceloods** [comment]
@joacimastrom I didn't receive a notification on your issue, so I apologize for taking so long to respond. Do you still get this bug? I just tried the extension as-is on the new Netflix UI on latest Chrome and it skipped the intro as expected, no auto-pausing. If it's not working properly, make sure to refresh the page once and try again. Let me know -- I'm getting notifications now.

**Comment by joacimastrom** [comment]
It seems a bit inconsistent, it sometimes works as expected, sometimes it pauses. I'll continue using it as-is and see if it resolves itself, otherwise try to pinpoint what's going on

**Comment by jrasch** [comment]
I can confirm this change resolves the issue.

The video only pauses when the controls are hidden. Attempting to test the behavior of the current extension release by, for example, moving the slider just before the title scene causes the controls to display and the video will continue playing without issue.

**Comment by joacimastrom** [comment]
Would simulating movement to display the controls be a more viable solution? The play-button does not have any suitable selectors, hence I had to use '.svg-icon-nfplayerPlay', which seems a bit brittle.

**Comment by jrasch** [comment]
I imagine that could work, but I don't know the capabilities of a Chrome extension. Perhaps there is a different selector (e.g. a container) that you could click first before the skip button? Or maybe just double-clicking the button would work?

**Comment by joacimastrom** [comment]
@joaomarceloods Problem persists, check jrash's comment above. 

I changed the selector to the actual play-button. You think we can merge it?

Edit: Reverted this, appears the button isn't actually changed and picked up by observer, only icon is.

**Pull request closed without merging**
